const states = [
	"Andaman & Nicobar",
	"Andhra Pradesh",
	"Arunachal Pradesh",
	"Assam",
	"Bihar",
	"Chandigarh",
	"Chhattisgarh",
	"Dadra & Nagar Haveli",
	"Daman & Diu",
	"Delhi",
	"Goa",
	"Gujarat",
	"Haryana",
	"Himachal Pradesh",
	"Jammu & Kashmir",
	"Jharkhand",
	"Karnataka",
	"Kerala",
	"Lakshadweep",
	"Madhya Pradesh",
	"Maharashtra",
	"Manipur",
	"Meghalaya",
	"Mizoram",
	"Nagaland",
	"Odisha",
	"Pondicherry",
	"Punjab",
	"Rajasthan",
	"Sikkim",
	"Telangana",
	"Tamil Nadu",
	"Tripura",
	"Uttar Pradesh",
	"Uttaranchal",
	"West Bengal",
];

export default states;
